import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const montserrat = localFont({
  src: [
    {
      path: "../fonts/Montserrat-VariableFont_wght.ttf",
      style: "normal",
      weight: "400",
    },
  ],
  variable: "--font-montserrat",
});
export const metadata = {
  title: "Oloniyo-Bolaji's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} max-w-screen mx-auto bg-[#0D1117]`}>
        <Navbar />
        {children}
        <ToastContainer autoClose={2000} position="top-left" />
      </body>
    </html>
  );
}
