import "./globals.css";
import Navbar from "@/components/Navbar";
import { Merriweather } from "next/font/google";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const merriweather = Merriweather({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Oloniyo-Bolaji's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} bg-background`}>
        <Navbar />
        {children}
        <ToastContainer autoClose={2000} position = 'top-left'/>
      </body>
    </html>
  );
}
